export const EXERCISE_GROUPS = {
  "Peito": [
    "Supino Reto com Barra",
    "Supino Reto com Halteres",
    "Supino Inclinado com Barra",
    "Supino Inclinado com Halteres",
    "Supino Declinado com Barra",
    "Supino Declinado com Halteres",
    "Crucifixo Reto",
    "Crucifixo Inclinado",
    "Crossover na Polia Alta",
    "Crossover na Polia Baixa",
    "Voador (Peck Deck)",
    "Flexão de Braços (Tradicional)",
    "Flexão de Braços (Inclinada/Declinada)",
    "Pullover com Halter",
    "Supino Máquina",
    "Crossover Unilateral"
  ],
  "Costas": [
    "Puxada Frontal (Pronada)",
    "Puxada Frontal (Supinada)",
    "Puxada com Triângulo",
    "Remada Curvada com Barra",
    "Remada Curvada Supinada (Yates Row)",
    "Remada Unilateral (Serrote)",
    "Remada Baixa (Triângulo)",
    "Remada Máquina Articulada",
    "Barra Fixa (Pull-up)",
    "Barra Fixa Supinada (Chin-up)",
    "Levantamento Terra (Deadlift)",
    "Pulldown com Corda",
    "Pulldown com Barra Reta",
    "Remada Cavalinho (T-Bar Row)",
    "Crucifixo Invertido Máquina",
    "Crucifixo Invertido com Halteres",
    "Hiperextensão Lombar"
  ],
  "Pernas (Quadríceps, Posterior e Glúteos)": [
    "Agachamento Livre (Barbell Squat)",
    "Agachamento Frontal (Front Squat)",
    "Agachamento Hack",
    "Agachamento Búlgaro",
    "Agachamento Sumô",
    "Agachamento Cálice (Goblet Squat)",
    "Leg Press 45º",
    "Leg Press Horizontal",
    "Cadeira Extensora",
    "Levantamento Terra Romeno (RDL)",
    "Stiff com Barra",
    "Stiff com Halteres",
    "Mesa Flexora",
    "Cadeira Flexora",
    "Flexão Nordica",
    "Elevação Pélvica (Hip Thrust)",
    "Afundo (Lunge)",
    "Passada (Walking Lunges)",
    "Cadeira Abdutora",
    "Cadeira Adutora",
    "Glúteo na Polia",
    "Panturrilha em Pé (Máquina)",
    "Panturrilha Sentado (Solear)",
    "Panturrilha no Leg Press"
  ],
  "Ombros": [
    "Desenvolvimento Militar com Barra",
    "Desenvolvimento com Halteres",
    "Desenvolvimento na Máquina",
    "Desenvolvimento Arnold",
    "Elevação Lateral com Halteres",
    "Elevação Lateral na Polia",
    "Elevação Frontal com Barra",
    "Elevação Frontal com Halteres",
    "Elevação Frontal na Polia",
    "Crucifixo Invertido (Traseiro de Ombro)",
    "Remada Alta com Barra",
    "Remada Alta na Polia",
    "Encolhimento com Barra (Trapézio)",
    "Encolhimento com Halteres (Trapézio)"
  ],
  "Braços (Bíceps e Tríceps)": [
    "Rosca Direta com Barra W/Reta",
    "Rosca Alternada com Halteres",
    "Rosca Martelo",
    "Rosca Concentrada",
    "Rosca Scott (Máquina ou Banco)",
    "Rosca na Polia Baixa",
    "Rosca Inversa",
    "Tríceps Testa com Barra W",
    "Tríceps Francesa (Halter ou Polia)",
    "Tríceps Pulley Reta",
    "Tríceps Pulley Corda",
    "Tríceps Coice (Kickback)",
    "Tríceps Banco (Mergulho)",
    "Mergulho nas Paralelas (Dips)",
    "Tríceps Suinado na Polia"
  ],
  "Abdômen e Core": [
    "Abdominal Supra Tradicional",
    "Abdominal Infra (Elevação de Pernas)",
    "Abdominal Infra na Barra Fixa",
    "Prancha Isométrica",
    "Prancha Lateral",
    "Abdominal Roda (Ab Wheel)",
    "Abdominal máquina",
    "Abdominal na Polia alta (Crunch na Polia)",
    "Giro Russo (Russian Twist)",
    "Abdominal Oblíquo",
    "V-Up",
    "Canivete"
  ]
};
